fixtures:
  repositories:
    'stdlib': 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    'systemd': 'https://github.com/camptocamp/puppet-systemd.git'
    'inifile': 'https://github.com/puppetlabs/puppetlabs-inifile.git'
    'lldpd': 'https://github.com/voxpupuli/puppet-lldpd.git'
    'archive': 'https://github.com/voxpupuli/puppet-archive.git'
    'tftp': 'https://github.com/theforeman/puppet-tftp.git'
    'vcsrepo': 'https://github.com/puppetlabs/puppetlabs-vcsrepo.git'
    'nginx': 'https://github.com/voxpupuli/puppet-nginx.git'
    'megaraid': 'https://github.com/m4ce/puppet-megaraid.git'
    'disk_facter': 'https://github.com/CygnusNetworks/cygnus-puppet-disk-facter.git'
    'concat': 'https://github.com/puppetlabs/puppetlabs-concat.git'
    'ferm': 'https://github.com/voxpupuli/puppet-ferm.git'
    'samba': 'https://github.com/kakwa/puppet-samba.git'
    'augeasproviders_pam': 'https://github.com/hercules-team/augeasproviders_pam.git'
    'kerberos':
      'repo': 'https://github.com/bastelfreak/puppet-kerberos.git'
      'branch': 'archlinux'
    'puppet': 'https://github.com/theforeman/puppet-puppet.git'
    'foreman': 'https://github.com/theforeman/puppet-foreman.git'
    'foreman_proxy': 'https://github.com/theforeman/puppet-foreman_proxy.git'
    'puppetdb': 'https://github.com/puppetlabs/puppetlabs-puppetdb.git'
    'postgresql': 'https://github.com/puppetlabs/puppetlabs-postgresql.git'
    'apache': 'https://github.com/puppetlabs/puppetlabs-apache.git'
    'extlib': 'https://github.com/voxpupuli/puppet-extlib.git'
    'foreman': 'https://github.com/theforeman/puppet-foreman.git'
    'xinetd': 'https://github.com/puppetlabs/puppetlabs-xinetd.git'
    'selinux': 'https://github.com/voxpupuli/puppet-selinux.git'
    'datacat': 'https://github.com/richardc/puppet-datacat.git'
